export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <style>{`
          html, body {
            margin: 0 !important;
            padding: 0 !important;
            box-sizing: border-box;
            width: 100vw;
            min-height: 100vh;
            background: transparent;
          }
        `}</style>
      </head>
      <body>{children}</body>
    </html>
  )
}
